# Generated by Django 2.1.15 on 2020-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', max_length=100, verbose_name='Post Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=100, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Post UID'),
        ),
    ]
