# Generated by Django 2.1.15 on 2020-05-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200416_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_isEnabled',
            field=models.BooleanField(default=True, verbose_name='Post Enabled'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Post Views'),
        ),
    ]
