# Generated by Django 2.1.15 on 2020-05-05 23:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_auto_20200416_2159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_uid', models.AutoField(primary_key=True, serialize=False, verbose_name='Page UID')),
                ('page_title', models.CharField(max_length=100, verbose_name='Page Title')),
                ('page_content', models.TextField(verbose_name='Page Content')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Page Views')),
                ('page_isEnabled', models.BooleanField(default=False, verbose_name='Page enabled')),
                ('page_crte_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('page_mdfy_dt', models.DateTimeField(auto_now=True, verbose_name='Modified DateTime')),
                ('menu', models.ForeignKey(db_column='menu_uid', on_delete=django.db.models.deletion.PROTECT, related_name='menu_page', to='menu.Menu', verbose_name='Menu')),
                ('page_crte_user', models.ForeignKey(db_column='page_crte_user_id', default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_page_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('page_mdfy_user', models.ForeignKey(db_column='page_mdfy_user_id', default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_page_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'db_table': 'blog_page',
                'ordering': ['-page_uid'],
            },
        ),
    ]
