# Generated by Django 2.1.15 on 2020-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Menu UID'),
        ),
    ]
