# Generated by Django 2.1.15 on 2020-04-16 21:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttFile',
            fields=[
                ('att_uid', models.AutoField(primary_key=True, serialize=False, verbose_name='Attachment File UID')),
                ('att_name', models.CharField(max_length=256, verbose_name='Attachment File Name')),
                ('att_path', models.CharField(max_length=512, unique=True, verbose_name='Attachment File Path')),
                ('att_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment File')),
                ('att_isImage', models.BooleanField(default=False, verbose_name='Image file whether or not')),
                ('att_desc', models.TextField(blank=True, null=True, verbose_name='Attachment File Description')),
                ('object_uid', models.PositiveIntegerField(db_index=True, verbose_name='Related Object UID')),
                ('att_crte_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('att_mdfy_dt', models.DateTimeField(auto_now=True, verbose_name='Modified DateTime')),
                ('att_crte_user', models.ForeignKey(db_column='att_crte_user_id', default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='att_post_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('att_mdfy_user', models.ForeignKey(db_column='att_mdfy_user_id', default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='att_post_modifier', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
                ('content_type', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='contentType_attFile', to='contenttypes.ContentType', verbose_name='ContentType')),
            ],
            options={
                'verbose_name': 'attFile',
                'verbose_name_plural': 'attFiles',
                'db_table': 'blog_attFile',
                'ordering': ['att_uid'],
            },
        ),
    ]
