# Generated by Django 2.1.15 on 2020-04-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attfile',
            name='att_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Attachment File Description'),
        ),
    ]
