# Generated by Django 2.1.15 on 2020-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attFile', '0002_auto_20200416_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attfile',
            name='att_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment File'),
        ),
    ]
