# Generated by Django 2.1.15 on 2020-04-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attFile', '0003_auto_20200418_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attfile',
            name='att_path',
        ),
        migrations.AlterField(
            model_name='attfile',
            name='att_file',
            field=models.FileField(blank=True, max_length=512, unique=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment File'),
        ),
    ]
