# Generated by Django 2.1.15 on 2020-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attFile', '0005_auto_20200501_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attfile',
            name='att_size',
            field=models.BigIntegerField(default=0, verbose_name='Attachment File Size'),
        ),
    ]
