# Generated by Django 2.1.15 on 2020-05-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attFile', '0006_auto_20200501_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attfile',
            name='att_size',
        ),
    ]
